// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace dodona_vs_extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "dodona_vs_extension.ba02502e-e7db-4291-92d8-ab8a98899b72";
        public const string Name = "Dodona Visual Studio Extension";
        public const string Description = @"A Visual Studio extension to submit exercises to Dodona.

";
        public const string Language = "en-US";
        public const string Version = "1.0.0";
        public const string Author = "Joren Synaeve";
        public const string Tags = "";
    }
}
