// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace dodona_vs_extension
{
    internal sealed partial class Vsix
    {
        public const string Id = "dodona_vs_extension.ba02502e-e7db-4291-92d8-ab8a98899b72";
        public const string Name = "dodona_vs_extension";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Joren Synaeve";
        public const string Tags = "";
    }
}
